Repository ohsu-comp-bio/funnel, pull requests merged in 2025-01, with the labels that each got.

#1107 `fix/pvc` — Support for multi-node scheduling and S3-backed working directories (S3 Mountpoint CSI)
  .github/workflows/build.yml
  .github/workflows/k8s.yaml
  Dockerfile
  README.md
  compute/kubernetes/backend.go
  config/config.go
  config/default-config.yaml
  config/default.go
  config/internal/bundle.go
  config/kubernetes-executor-template.yaml
  config/kubernetes-pv.yaml
  config/kubernetes-pvc.yaml
  config/kubernetes-template.yaml
  deployments/kubernetes/helm/Chart.yaml
  deployments/kubernetes/helm/config/funnel-server.yaml
  deployments/kubernetes/helm/config/funnel-worker.yaml
  deployments/kubernetes/helm/templates/NOTES.txt
  deployments/kubernetes/helm/templates/clusterrole.yaml
  deployments/kubernetes/helm/templates/clusterrolebinding.yaml
  deployments/kubernetes/helm/templates/role.yaml
  deployments/kubernetes/helm/values.yaml
  examples/internal/bundle.go
  funnel.config.yml
  go.mod
  go.sum
  website/content/docs/compute/kubernetes.md
  website/static/img/k8s-pvc.png
  worker/kubernetes.go
  worker/worker.go
Labels: bug, enhancement

#1098 `feature/credentials` Per-User/Per-Bucket Support
  website/content/docs/security/advanced.md
Labels: enhancement, docs

#1110 OIDC-based user authentication
  cmd/server/run.go
  config/config.go
  config/default-config.yaml
  go.mod
  go.sum
  server/auth.go
  server/auth_oidc.go
  server/server.go
  webdash/src/CancelButton.js
  webdash/src/Pages.js
  webdash/src/utils.js
  webdash/web.go
  website/content/docs/security/oauth2.md
Labels: enhancement, feature
